name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.453828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030200'
    - '#FFFFFF'
    - '#685944'
    - '#BCAEA1'
    - '#412309'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
