typography_spectrum: 0.19065380352549255
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.39989672554656863
  lightness: 0.01659549679607153
  saturation: 0.16107737109996378
  rhythmicContrast: 0.12872153567150235
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.36711767595261335
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
name: Pierre Sottas - Bass // Acoustic Bass // Arranger // Producer
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Projects
    id: 8bcf99d2-c978-4012-aca8-0112cf846f60
    type: content
  - name: Arranging
    id: 046607f1-d02d-4819-bbd7-4af92e8cdf15
    type: content
  - name: Contact
    id: 6b6482d9-05f9-4dfa-a4e7-7ce23b83672b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2ca13d0d-623f-49ac-b938-94efed1aa0ae.jpg
title: Bass // Acoustic Bass // Arranger // Producer
description: Bass // Acoustic Bass // Arranger // Producer
purpose: []
