layout_spectrum: 0.1532946830684559
typography_spectrum: 0.49457912117547104
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.7131611490280063
  lightness: 0.669659687225421
  saturation: 0.4981835622636435
  rhythmicContrast: 0.5979482860890871
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-87765996-1
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  email: pierre.sottas@cheesecom.com
  url: www.pierresottas.net
name: Pierre Sottas
url: 'http://pierresottas.net'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    id: a154b4e4-a81a-4603-9ac7-7ff189c361be
    type: content
  - name: Projects
    id: 8bcf99d2-c978-4012-aca8-0112cf846f60
    type: content
  - name: Arranging
    id: 046607f1-d02d-4819-bbd7-4af92e8cdf15
    type: content
  - name: Contact
    id: 6b6482d9-05f9-4dfa-a4e7-7ce23b83672b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2ca13d0d-623f-49ac-b938-94efed1aa0ae.jpg
title: Pierre Sottas
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/95585d3f-717a-400f-b1c6-f08ca4cdf56c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/95585d3f-717a-400f-b1c6-f08ca4cdf56c.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Bass // Acoustic Bass // Arranger // Producer
purpose: []
