typography_spectrum: 0.6115993047133088
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.9730581850744784
  lightness: 0.3134595991577953
  saturation: 0.6998962473589927
  rhythmicContrast: 0.10539798904210329
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.37465380714274943
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  email: pierre.sottas@cheesecom.com
  url: www.cheesecom.com
name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2ca13d0d-623f-49ac-b938-94efed1aa0ae.jpg
title: 'bass, acoustic bass, arranger, producer'
purpose: []
