name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.58554
title: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030200'
    - '#ffffff'
    - '#685944'
    - '#bcaea1'
    - '#412309'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
