analytics: {}
color:
  brandColors:
    - '#030200'
    - '#FFFFFF'
    - '#685944'
    - '#BCAEA1'
    - '#412309'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.492117
cta: {}
layout_spectrum: 0.203828
name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
opengraph: {}
purpose: []
typography_spectrum: 0.453828
