name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
favicon: null
layout_spectrum: 0.863
typography_spectrum: 0
title: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8f91c7'
    - '#010310'
    - '#464a83'
    - '#2a2a52'
    - '#b2b1df'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
