name: Pierre Sottas
favicon: null
layout_spectrum: 0.75536
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8f91c7'
    - '#010310'
    - '#464a83'
    - '#2a2a52'
    - '#b2b1df'
  brandStrength: 0.75
  lightness: 0.7401955537497997
  saturation: 0.5
  rhythmicContrast: 0.6359048187732697
purpose: []
