name: Pierre Sottas
favicon: null
layout_spectrum: 0.49805609532631934
typography_spectrum: 0.1457768592517823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.04612170928157866
  lightness: 0.7401955537497997
  saturation: 0.07295010122470558
  rhythmicContrast: 0.6359048187732697
purpose: []
