name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
favicon: null
layout_spectrum: 0.2434
typography_spectrum: 0.453828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0c0c0'
    - '#000000'
    - '#484848'
    - '#242424'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
