name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38387
title: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#282828'
    - '#7c7c7c'
    - '#9a9a9a'
    - '#e9e9e9'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
