name: 'Pierre Sottas - bass, acoustic bass, arranger, producer'
favicon: null
layout_spectrum: 0.37465380714274943
typography_spectrum: 0.6115993047133088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.9730581850744784
  lightness: 0.3134595991577953
  saturation: 0.6998962473589927
  rhythmicContrast: 0.10539798904210329
purpose: []
