layout_spectrum: 0.42300402560105343
typography_spectrum: 0.46453024427867545
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.7384010347848444
  lightness: 0.6203091235954019
  saturation: 0.05470808617042212
  rhythmicContrast: 0.4136351074865733
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-87765996-1
  facebook: null
  twitter: null
author:
  name: Pierre Sottas
  email: pierre.sottas@cheesecom.com
  url: www.pierresottas.net
name: Pierre Sottas
url: 'http://www.pierresottas.net'
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    id: a154b4e4-a81a-4603-9ac7-7ff189c361be
    type: content
  - name: Projects
    id: 8bcf99d2-c978-4012-aca8-0112cf846f60
    type: content
  - name: Arranging
    id: 046607f1-d02d-4819-bbd7-4af92e8cdf15
    type: content
  - name: Contact
    id: 6b6482d9-05f9-4dfa-a4e7-7ce23b83672b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2ca13d0d-623f-49ac-b938-94efed1aa0ae.jpg
title: Pierre Sottas
content: []
description: Bass // Acoustic Bass // Arranger // Producer
purpose: []
